# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Beer_List' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Beer_List

pod 'RxSwift'
pod 'RxCocoa'
pod 'Alamofire'
pod 'Kingfisher'
pod 'LayoutHelper'
pod 'RxAlamofire'

end
